tetragon:
  exportAllowList: |-
    {"event_set":["PROCESS_EXEC", "PROCESS_EXIT", "PROCESS_KPROBE", "PROCESS_UPROBE", "PROCESS_TRACEPOINT"]}
  enablePolicyFilter: true
  enableProcessCred: true
  enableProcessNs: true
export:
  mode: stdout
  filenames:
  - tetragon.log