version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    labels:
      - ci/dependabot
      - kind/enhancement
  - package-ecosystem: "terraform"
    directory: /example
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    labels:
      - ci/dependabot
      - kind/enhancement